name: Create S3 Bucket and Key Pair

on:
    workflow_dispatch:

jobs:
  create-resources:
    runs-on: ubuntu-latest
    env:
        BUCKET_NAME: ${{ vars.TF_VAR_PROJECT_NAME }}-terraform-backend-${{ secrets.AWS_REGION }}
        KEY_PAIR_NAME: ${{ vars.TF_VAR_PROJECT_NAME }}-kp

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Create S3 Bucket
      run: |
        aws s3api create-bucket --bucket $BUCKET_NAME --region ${{ secrets.AWS_REGION }} --create-bucket-configuration LocationConstraint=${{ secrets.AWS_REGION }}

    - name: Enable Versioning on S3 Bucket
      run: |
          aws s3api put-bucket-versioning --bucket $BUCKET_NAME --versioning-configuration Status=Enabled
  
    - name: Generate Key Pair
      run: |
        aws ec2 create-key-pair --key-name $KEY_PAIR_NAME --query 'KeyMaterial' --output text > $KEY_PAIR_NAME.pem
        chmod 400 $KEY_PAIR_NAME.pem

    - name: Upload PEM to S3
      run: |
        aws s3 cp $KEY_PAIR_NAME.pem s3://$BUCKET_NAME/pem/$KEY_PAIR_NAME.pem
