name: Terraform Apply

on:
    workflow_dispatch: 

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4

      - name: Terraform Init
        run: terraform init --reconfigure --backend-config="bucket=${{ vars.TF_VAR_PROJECT_NAME }}-terraform-backend-${{ secrets.AWS_REGION }}"

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        env:
            TF_VAR_project_name: ${{ vars.TF_VAR_PROJECT_NAME }}
            TF_VAR_environment: ${{ vars.TF_VAR_ENVIRONMENT }}
            TF_VAR_vpc_name: ${{ vars.TF_VAR_VPC_NAME }}
            TF_VAR_vpc_cidr: ${{ vars.TF_VAR_VPC_CIDR }}
